# Generated by Django 5.0.4 on 2025-09-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Tapara Dev', max_length=100, verbose_name='Nombre de la Empresa')),
                ('tagline', models.CharField(default='Desarrollo de aplicaciones web, móviles e integraciones', max_length=200, verbose_name='Lema')),
                ('about_text', models.TextField(verbose_name='Texto de Acerca De')),
                ('mission', models.TextField(blank=True, null=True, verbose_name='Misión')),
                ('vision', models.TextField(blank=True, null=True, verbose_name='Visión')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Información de la Empresa',
                'verbose_name_plural': 'Información de la Empresa',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leído')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Proyecto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('short_description', models.CharField(max_length=200, verbose_name='Descripción Corta')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Imagen')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL del Proyecto')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='URL de GitHub')),
                ('technologies', models.CharField(help_text='Separadas por comas', max_length=200, verbose_name='Tecnologías Utilizadas')),
                ('status', models.CharField(choices=[('completed', 'Completado'), ('in_progress', 'En Progreso'), ('planned', 'Planificado')], default='completed', max_length=20, verbose_name='Estado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Servicio')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('short_description', models.CharField(help_text='Descripción breve para mostrar en tarjetas', max_length=200, verbose_name='Descripción Corta')),
                ('icon', models.CharField(default='fas fa-code', help_text='Clase CSS del icono (ej: fas fa-code)', max_length=50, verbose_name='Icono')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('bio', models.TextField(verbose_name='Biografía')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Foto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Miembro del Equipo',
                'verbose_name_plural': 'Miembros del Equipo',
                'ordering': ['order', 'name'],
            },
        ),
    ]
